package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@SpringBootApplication
@RestController
public class SpringStart035Application {

	public static void main(String[] args) {
		SpringApplication.run(SpringStart035Application.class, args);
	}

	@RequestMapping("/helloSpring5")
	public String index(
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType(MediaType.TEXT_HTML_VALUE);
		String content = """
				<!DOCTYPE html>
				<html>
				<head>
				<meta charset="UTF-8">
				<title>Hello Spring 5</title>
				</head>
				<body>
				<h1>Hello Spring 5</h1>
				<p>This is a sample page generated by Spring Boot.</p>
				</body>
				</html>
				""";
		return content;
	}
}
